version: '3'
services:
  db:
    image: postgres
    build: db
    restart: always
    environment:
      POSTGRES_USER: django_challenge
      POSTGRES_PASSWORD: GT8XmPY2xvENgpGz
      POSTGRES_DB: django_challenge
    volumes:
      - './db/data:/var/lib/postgresql/data'
    ports:
      - '5433:5432'
  web:
    build: src
    image: python
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - './src:/app/'
    ports:
      - '3000:3000'
      - '8000:8000'
    depends_on:
      - db
